s3:
  bucket_name: "usecase-2"
  filepath: "Input_data/Input_data.csv"

features:
  target_col: "TARGET"
  drop_col: "HCO_Affiliation"
  onehot_cols: ['Sex', 'Specialty', 'HCO_Affiliation_Type']
  id_target_col_list: ['NPI_ID', 'HCP_ID', 'TARGET']
  id_col_list : ['NPI_ID', 'HCP_ID']
  value_replace : 'Sex'

feature-store:
             lookup_key: ["HCP_ID","NPI_ID"]
             table_name: "usecase2_table"
             final_features_table : "usecase2_features"

cleaned_data:
           preprocessed_df_path: 'preprocessed/preprocessed_df.csv'
           final_features_df_path: 'preprocessed/final_features_df.csv'

variance:
  threshold: 0.1

kbestfeatures:
  no_of_features: 20


split :
  test_split : 0.1
  val_split : 0.2

Mlflow :
  experiment_name : 'usecase2_ml'





