s3:
  bucket_name: "usecase-2"
  filepath: "Input_data/Input_data.csv"
  figure_path : figures/summary_plot.png
  X_test: Input_data/X_test.csv

features:
  target_col: "TARGET"
  drop_col: "HCO_Affiliation"
  onehot_cols: ['Sex', 'Specialty', 'HCO_Affiliation_Type']
  id_target_col_list: ['NPI_ID', 'HCP_ID', 'TARGET']
  id_col_list : ['NPI_ID', 'HCP_ID']
  value_replace : 'Sex'

  numerical_features : ['Age', 'Number_of_Rx', 'Rx_last_1_Month',
       'Rx_last_3_Month', 'Rx_last_6_Month', 'Rx_last_12_Month',
       'Claims_last_1_Month', 'Claims_last_3_Month',
       'Procedures_chemo_last_1_month', 'Procedures_chemo_last_3_month',
       'Procedures_chemo_last_6_month', 'Procedures_chemo_last_12_month',
       'Procedures_radio_last_1_month', 'Procedures_Immuno_last_6_month',
       'Procedures_Immuno_last_12_month', 'Procedures_Biopsy_last_3_month',
       'Procedures_Biopsy_last_6_month', 'Procedures_Biopsy_last_12_month',
       'Promotional_medscape_last_1_month',
       'Promotional_medscape_last_3_month',
       'Promotional_medscape_last_6_month', 'F2F_visit',
       'F2F_visit_last_1_month', 'F2F_visit_last_3_month',
       'VRC_visit_last_3_month', 'VRC_visit_last_6_month',
       'VRC_visit_last_12_month']
  categorical_features : ['HCO_Affiliation_Type_Contract',
       'HCO_Affiliation_Type_Referral']

feature-store:
             lookup_key: ["HCP_ID","NPI_ID"]
             table_name: "phy_table"
             final_features_table : "usecase2_features"
             online_table_name : "usecase2_online_table2"

cleaned_data:
           preprocessed_df_path: 'preprocessed/preprocessed_df.csv'
           final_features_df_path: 'preprocessed/final_features_df.csv'

variance:
  threshold: 0.1

kbestfeatures:
  no_of_features: 10


split :
  test_split : 0.1
  val_split : 0.2

Mlflow :
  experiment_name : "/Shared/dbx/usecase2_ml"

params :
 colsample_bytree: 0.80
 gamma': 0.0
 max_depth': 7
 reg_alpha: 0.2
 subsample': 0.19

deployment-pipeline :
    job_id: '732974406178905'

databricks-url : "https://dbc-34a6125d-ed23.cloud.databricks.com/"






